# locations.py

COUNTRIES = [
    {"label": "All Countries", "value": "All"},
    {"label": "USA", "value": "USA"},
    {"label": "Canada", "value": "Canada"},
    {"label": "Mexico", "value": "Mexico"},
    {"label": "Australia", "value": "Australia"},
    {"label": "China", "value": "China"},
    {"label": "India", "value": "India"},
    {"label": "Israel", "value": "Israel"},
    {"label": "Brazil", "value": "Brazil"},
    {"label": "Türkiye", "value": "Türkiye"},
    {"label": "Chinese Taipei", "value": "Chinese Taipei"},
]

STATES = {
    "USA": [
        {"label": "Alabama", "value": "Alabama"},
        {"label": "Alaska", "value": "Alaska"},
        {"label": "Arizona", "value": "Arizona"},
        {"label": "Arkansas", "value": "Arkansas"},
        {"label": "California", "value": "California"},
        {"label": "Colorado", "value": "Colorado"},
        {"label": "Connecticut", "value": "Connecticut"},
        {"label": "Delaware", "value": "Delaware"},
        {"label": "Florida", "value": "Florida"},
        {"label": "Georgia", "value": "Georgia"},
        {"label": "Hawaii", "value": "Hawaii"},
        {"label": "Idaho", "value": "Idaho"},
        {"label": "Illinois", "value": "Illinois"},
        {"label": "Indiana", "value": "Indiana"},
        {"label": "Iowa", "value": "Iowa"},
        {"label": "Kansas", "value": "Kansas"},
        {"label": "Kentucky", "value": "Kentucky"},
        {"label": "Louisiana", "value": "Louisiana"},
        {"label": "Maine", "value": "Maine"},
        {"label": "Maryland", "value": "Maryland"},
        {"label": "Massachusetts", "value": "Massachusetts"},
        {"label": "Michigan", "value": "Michigan"},
        {"label": "Minnesota", "value": "Minnesota"},
        {"label": "Mississippi", "value": "Mississippi"},
        {"label": "Missouri", "value": "Missouri"},
        {"label": "Montana", "value": "Montana"},
        {"label": "Nebraska", "value": "Nebraska"},
        {"label": "Nevada", "value": "Nevada"},
        {"label": "New Hampshire", "value": "New Hampshire"},
        {"label": "New Jersey", "value": "New Jersey"},
        {"label": "New Mexico", "value": "New Mexico"},
        {"label": "New York", "value": "New York"},
        {"label": "North Carolina", "value": "North Carolina"},
        {"label": "North Dakota", "value": "North Dakota"},
        {"label": "Ohio", "value": "Ohio"},
        {"label": "Oklahoma", "value": "Oklahoma"},
        {"label": "Oregon", "value": "Oregon"},
        {"label": "Pennsylvania", "value": "Pennsylvania"},
        {"label": "Rhode Island", "value": "Rhode Island"},
        {"label": "South Carolina", "value": "South Carolina"},
        {"label": "South Dakota", "value": "South Dakota"},
        {"label": "Tennessee", "value": "Tennessee"},
        {"label": "Texas", "value": "Texas"},
        {"label": "Utah", "value": "Utah"},
        {"label": "Vermont", "value": "Vermont"},
        {"label": "Virginia", "value": "Virginia"},
        {"label": "Washington", "value": "Washington"},
        {"label": "West Virginia", "value": "West Virginia"},
        {"label": "Wisconsin", "value": "Wisconsin"},
        {"label": "Wyoming", "value": "Wyoming"},
    ],
    "Canada": [
        {"label": "Alberta", "value": "Alberta"},
        {"label": "British Columbia", "value": "British Columbia"},
        {"label": "Manitoba", "value": "Manitoba"},
        {"label": "New Brunswick", "value": "New Brunswick"},
        {"label": "Newfoundland and Labrador", "value": "Newfoundland and Labrador"},
        {"label": "Nova Scotia", "value": "Nova Scotia"},
        {"label": "Ontario", "value": "Ontario"},
        {"label": "Prince Edward Island", "value": "Prince Edward Island"},
        {"label": "Quebec", "value": "Quebec"},
        {"label": "Saskatchewan", "value": "Saskatchewan"},
    ],
    "Mexico": [
        {"label": "Aguascalientes", "value": "Aguascalientes"},
        {"label": "Baja California", "value": "Baja California"},
        {"label": "Chihuahua", "value": "Chihuahua"},
        {"label": "Coahuila", "value": "Coahuila"},
        {"label": "Jalisco", "value": "Jalisco"},
        {"label": "Mexico City", "value": "Mexico City"},
        {"label": "Nuevo León", "value": "Nuevo León"},
        {"label": "Puebla", "value": "Puebla"},
        {"label": "Querétaro", "value": "Querétaro"},
        {"label": "Yucatán", "value": "Yucatán"},
    ],
    "Australia": [
        {"label": "New South Wales", "value": "New South Wales"},
        {"label": "Queensland", "value": "Queensland"},
        {"label": "South Australia", "value": "South Australia"},
        {"label": "Tasmania", "value": "Tasmania"},
        {"label": "Victoria", "value": "Victoria"},
        {"label": "Western Australia", "value": "Western Australia"},
    ],
    "India": [
        {"label": "Delhi", "value": "Delhi"},
        {"label": "Karnataka", "value": "Karnataka"},
        {"label": "Maharashtra", "value": "Maharashtra"},
        {"label": "Tamil Nadu", "value": "Tamil Nadu"},
        {"label": "Uttar Pradesh", "value": "Uttar Pradesh"},
    ],
}

STATES.update({
    "Israel": [
        {"label": "Central District", "value": "Central District"},
        {"label": "Haifa District", "value": "Haifa District"},
        {"label": "Jerusalem District", "value": "Jerusalem District"},
        {"label": "Northern District", "value": "Northern District"},
        {"label": "Southern District", "value": "Southern District"},
        {"label": "Tel Aviv District", "value": "Tel Aviv District"},
    ],
    "Türkiye": [
        {"label": "Adana", "value": "Adana"},
        {"label": "Ankara", "value": "Ankara"},
        {"label": "Antalya", "value": "Antalya"},
        {"label": "Bursa", "value": "Bursa"},
        {"label": "Istanbul", "value": "Istanbul"},
        {"label": "Izmir", "value": "Izmir"},
        {"label": "Konya", "value": "Konya"},
        {"label": "Gaziantep", "value": "Gaziantep"},
        {"label": "Mersin", "value": "Mersin"},
        {"label": "Kayseri", "value": "Kayseri"},
        {"label": "Eskisehir", "value": "Eskisehir"},
    ],
    "Brazil": [
        {"label": "Acre", "value": "Acre"},
        {"label": "Alagoas", "value": "Alagoas"},
        {"label": "Amapá", "value": "Amapá"},
        {"label": "Amazonas", "value": "Amazonas"},
        {"label": "Bahia", "value": "Bahia"},
        {"label": "Ceará", "value": "Ceará"},
        {"label": "Distrito Federal", "value": "Distrito Federal"},
        {"label": "Espírito Santo", "value": "Espírito Santo"},
        {"label": "Goiás", "value": "Goiás"},
        {"label": "Maranhão", "value": "Maranhão"},
        {"label": "Mato Grosso", "value": "Mato Grosso"},
        {"label": "Mato Grosso do Sul", "value": "Mato Grosso do Sul"},
        {"label": "Minas Gerais", "value": "Minas Gerais"},
        {"label": "Pará", "value": "Pará"},
        {"label": "Paraíba", "value": "Paraíba"},
        {"label": "Paraná", "value": "Paraná"},
        {"label": "Pernambuco", "value": "Pernambuco"},
        {"label": "Piauí", "value": "Piauí"},
        {"label": "Rio de Janeiro", "value": "Rio de Janeiro"},
        {"label": "Rio Grande do Norte", "value": "Rio Grande do Norte"},
        {"label": "Rio Grande do Sul", "value": "Rio Grande do Sul"},
        {"label": "Rondônia", "value": "Rondônia"},
        {"label": "Roraima", "value": "Roraima"},
        {"label": "Santa Catarina", "value": "Santa Catarina"},
        {"label": "São Paulo", "value": "São Paulo"},
        {"label": "Sergipe", "value": "Sergipe"},
        {"label": "Tocantins", "value": "Tocantins"},
    ],
    "China": [
        {"label": "Anhui", "value": "Anhui"},
        {"label": "Beijing", "value": "Beijing"},
        {"label": "Chongqing", "value": "Chongqing"},
        {"label": "Fujian", "value": "Fujian"},
        {"label": "Gansu", "value": "Gansu"},
        {"label": "Guangdong", "value": "Guangdong"},
        {"label": "Guangxi", "value": "Guangxi"},
        {"label": "Guizhou", "value": "Guizhou"},
        {"label": "Hainan", "value": "Hainan"},
        {"label": "Hebei", "value": "Hebei"},
        {"label": "Heilongjiang", "value": "Heilongjiang"},
        {"label": "Henan", "value": "Henan"},
        {"label": "Hubei", "value": "Hubei"},
        {"label": "Hunan", "value": "Hunan"},
        {"label": "Inner Mongolia", "value": "Inner Mongolia"},
        {"label": "Jiangsu", "value": "Jiangsu"},
        {"label": "Jiangxi", "value": "Jiangxi"},
        {"label": "Jilin", "value": "Jilin"},
        {"label": "Liaoning", "value": "Liaoning"},
        {"label": "Ningxia", "value": "Ningxia"},
        {"label": "Qinghai", "value": "Qinghai"},
        {"label": "Shaanxi", "value": "Shaanxi"},
        {"label": "Shandong", "value": "Shandong"},
        {"label": "Shanghai", "value": "Shanghai"},
        {"label": "Shanxi", "value": "Shanxi"},
        {"label": "Sichuan", "value": "Sichuan"},
        {"label": "Tianjin", "value": "Tianjin"},
        {"label": "Tibet", "value": "Tibet"},
        {"label": "Xinjiang", "value": "Xinjiang"},
        {"label": "Yunnan", "value": "Yunnan"},
        {"label": "Zhejiang", "value": "Zhejiang"},
    ],
    "Chinese Taipei": [
        {"label": "Taipei", "value": "Taipei"},
        {"label": "New Taipei", "value": "New Taipei"},
        {"label": "Taichung", "value": "Taichung"},
        {"label": "Tainan", "value": "Tainan"},
        {"label": "Kaohsiung", "value": "Kaohsiung"},
        {"label": "Hsinchu", "value": "Hsinchu"},
        {"label": "Keelung", "value": "Keelung"},
        {"label": "Taoyuan", "value": "Taoyuan"},
        {"label": "Chiayi", "value": "Chiayi"},
    ],
})


