name: Auto Update Data + Deploy

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository using GH_PAT
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r team_data/requirements.txt

    - name: Run update scripts
      env:
        TBA_API_KEYS: ${{ secrets.TBA_API_KEYS }}
      run: |
        python team_data/createeventdb.py
        python team_data/createdb.py

    - name: Force commit and push updated databases
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        # Save generated files temporarily
        mkdir -p tmp_sqlite
        cp -f team_data/events.sqlite tmp_sqlite/events.sqlite
        cp -f team_data/epa_teams.sqlite tmp_sqlite/epa_teams.sqlite

        # Clear any Git index ignore/cache
        git update-index --assume-unchanged --no-assume-unchanged team_data/*.sqlite || true

        # Remove any previous index references
        git rm --cached team_data/events.sqlite team_data/epa_teams.sqlite || true

        # Restore the actual files after rm
        mv tmp_sqlite/events.sqlite team_data/events.sqlite
        mv tmp_sqlite/epa_teams.sqlite team_data/epa_teams.sqlite

        # Stage them and commit
        git add team_data/events.sqlite team_data/epa_teams.sqlite || true
        git commit --allow-empty -m "Force auto-update of databases"

        # Force push
        git push --force https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git main

    - name: Push to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_APP_NAME}.git
        git push heroku main
