name: Auto Update FRC Data + Deploy

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository using GH_PAT
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r team_data/requirements.txt

    - name: Run update scripts
      env:
        TBA_API_KEYS: ${{ secrets.TBA_API_KEYS }}
      run: |
        python team_data/createeventdb.py
        python team_data/createdb.py

    - name: Commit and push updated databases
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        git status
        git add team_data/events.sqlite team_data/epa_teams.sqlite || true
        git commit -m "Auto-update databases" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git main

    - name: Push to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_APP_NAME}.git
        git push heroku main
